# Generated by Django 4.1.4 on 2023-01-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downapp', '0004_auto_20230111_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='download_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='uploader',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
